Frontday/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'users/index'
  root 'home#index'
  devise_for :users
    
resources :users, only: [:index, :show ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Frontday/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Frontday/app/models/article.rb
class Article < ApplicationRecord
  
 belongs_to :user
 validates :title, :content, presence: true
end

Frontday/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
validates :fist_name, :last_name, :email, presence: true
validates :email, uniqueness: true
has_many :articles

end

Frontday/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:fist_name, :last_name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

Frontday/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

   before_action :current_user?, only: [:edit, :destroy]
 
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:user_id, :title, :content)
    end
        def current_user?
   if @article.user != current_user
       flash[:alert] = "You are not the owner."
       redirect_to articles_path
      end
   end
end

Frontday/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Frontday/app/controllers/users_controller.rb
class UsersController < ApplicationController
      before_action :current_user?, only: [:edit, :destroy, :card]
     def index
       @users = User.all
     end
       def current_user?
   if @user != current_user
       flash[:alert] = "You are not the owner."
       redirect_to users_path
   end
    end
def show
      @user = User.find(params[:id])
    end
def card


end
end

Frontday/app/helpers/application_helper.rb
module ApplicationHelper
end

Frontday/app/helpers/articles_helper.rb
module ArticlesHelper
end

Frontday/app/helpers/home_helper.rb
module HomeHelper
end

Frontday/app/helpers/users_helper.rb
module UsersHelper
end

Frontday/app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

Frontday/app/views/articles/edit.html.erb
<div class="page-header">
  <%= link_to articles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @article, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing article</h1>
</div>

<%= render 'form' %>

Frontday/app/views/articles/index.html.erb
<br>
<br>
<% if user_signed_in? %>
<div class="page-header">
  <%= link_to new_article_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Article
  <% end %>
  <h1 class="rainbow">Listing articles</h1>
  <br>
  <br>
</div>

<div class="table-responsive">
 
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User FirstName</th>
            <th>Title</th>
            <th>Content</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
      <% @articles.each do |article| %>

    <tbody>
            <td><%= article.user.fist_name %></td>
            <td><%= article.title %></td>
            <td><%= article.content %></td>
            <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure fdp ?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<br>
<br>
<br>
<br>
<h2 class="rainbow">Welcome , to see content of this website you must be <%= link_to 'registered', new_user_registration_path %></h2>
<%= link_to 'Create account', new_user_registration_path %>

<% end %>

Frontday/app/views/articles/new.html.erb
<% if user_signed_in? %>
<div class="page-header">
  <%= link_to articles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1 class="rainbow">Nouvelle Idée</h1>
</div>

<%= render 'form' %>
<% else %>


<h2 class="rainbow">Welcome , to see content of this website you must be <%= link_to 'registered', new_user_registration_path %></h2>
<%= link_to 'Create account', new_user_registration_path %>

<% end %>

Frontday/app/views/articles/show.html.erb
<% if user_signed_in? %>
<div class="page-header">
  <%= link_to articles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_article_path(@article), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show article</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @article.user %></dd>

  <dt>Title:</dt>
  <dd><%= @article.title %></dd>

  <dt>Content:</dt>
  <dd><%= @article.content %></dd>

</dl>
<% else %>
<br>
<br>
<br>
<br>
<h2>Welcome , to see content of this website you must be <%= link_to 'registered', new_user_registration_path %></h2>
<%= link_to 'Create account', new_user_registration_path %>

<% end %>

Frontday/app/views/home/index.html.erb
<% if user_signed_in? %>
<div class="page-header" >
  <h1 class="rainbow"> Welcome <%= current_user.fist_name %> </h1>
  <br>
  <br>
</div>

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="http://image.noelshack.com/fichiers/2018/46/2/1542141155-kisspng-astronaut-cartoon-clip-art-cute-astronaut-cliparts-5a854ed3b3b5c1-3921119215186859077361.png" alt="Card image cap[100%x180]" data-holder-rendered="true" style="height: 180px; width: 100%; display: block;>
  <div class="card-body">
    <h5 class="card-title"><%= current_user.fist_name  %>  <%= current_user.last_name  %></h5>
    <p class="card-text"  ><--Astronaute confirmé --></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">AstronauteIndustry</li>
  </ul>
  </div>


<br>
<p>You're succesfully registered</p>
<a style="margin: 0 auto; width:50%;" href="articles#index" class="btn btn-primary btn-lg btn-block ">Voir le contenu</a>

<% else %>


<h2 class="rainbow">Welcome , to see content of this website you must be <%= link_to 'registered', new_user_registration_path %></h2>
<%= link_to 'Create account', new_user_registration_path %>

<% end %>

Frontday/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Mon site à moi lol</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-logo"><li><a href="/"><img class="logo" class="navbar-left" src="http://image.noelshack.com/fichiers/2018/45/3/1541617446-earth.png"></a></li>
    </div>
    
    <div class="navbar-right" >
    <div class="dropdown">
    <button class="btn-dropdownavatar"><img style="top: 0px; right: 10px;" class="logoavatar" src="http://image.noelshack.com/fichiers/2018/46/2/1542116474-kisspng-smiley-emojipedia-astronaut-emoticon-space-astronaut-5b049510b79f75-7793679515270269607521.png">
      </button>
    <div class="dropdown-content">
      <a href="/users/index">Voir tous les potos</a>
      <a href="/">Profil</a>
      <a><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </a>
    </div>
  </div>
     

<!-- Tab content -->



      <ul class="nav navbar-nav">         

        <% if user_signed_in? %>
         
          <% else %>

           



          <li><a style="top: -10px; right: 10px;" href="/users/sign_in" class="rainbow" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Se connecter</a></li>
          <li><a style="top: -20px; right: 10px;" href="/users/sign_up" class="rainbow" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Devenir Astronaute</a></li>
         
          <% end %>
          <div class="tab">
               <a href="/articles/new" class="button" onclick="openCity(event, 'Pose ton idée')">Pose ton idée</a>
               <a href="/articles#show" class="button" onclick="openCity(event, 'Voir les idées')">Voir les idées</a>
          
          <li><a style="top: 0px; right: 10px;" href="/articles/new" class="rainbow" class="btn btn-primary btn-lg" role="button" aria-pressed="true">Pose ton idée</a></li>
          
         
          <li><a href="/articles#show" class="rainbow" >Voir les idées</a></li>
          
       
       </ul>
      </div>
      
      


 </nav>
  
  <div class="container" class="rainbow">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

Frontday/app/views/users/index.html.erb
<% if user_signed_in? %>
<div class="page-header">
   
  <h1 class="rainbow">Listing Users</h1>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Articles</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
            <% @users.each do |user| %>
    </thead>
    <tbody>
            <td><%= user.fist_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.articles.count %></td>
            <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
        <td><%= link_to 'Destroy', user_registration_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<h1 class="rainbow">This page is allowed for registered users only </h1>
<%= link_to 'register here' , new_user_session_path %>




<% end %>

Frontday/app/views/users/show.html.erb
<div>
<br>
<br>
<br>
<br>
<br>

     <dt>User:</dt>
           <dd><%= @user.fist_name %></td>
              <dd><%= @user.last_name %></td>
           <dd><%= @user.email %></td>

</div>